<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\StoreConfig;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

$storeConfig = $viewModels->require(StoreConfig::class);
$maxItemsToDisplay = $storeConfig->getStoreConfig('checkout/sidebar/max_items_display_count');

/** @var HeroiconsOutline $heroIcons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<script>
    function initCartDrawer() {
        return {
            open: false,
            isLoading: false,
            cart: {},
            maxItemsToDisplay: <?= (int) $maxItemsToDisplay ?>,
            itemsCount: 0,
            getData(data) {
                if (data.cart) {
                    this.cart = data.cart;
                    this.itemsCount = data.cart.items && data.cart.items.length || 0;
                    this.setCartItems();
                }
                this.isLoading = false;
            },
            cartItems: [],
            getItemCountTitle() {
                return hyva.strf('<?= $escaper->escapeJs(__('%0 of %1 products in cart displayed')) ?>', this.maxItemsToDisplay, this.itemsCount)
            },
            setCartItems() {
                this.cartItems = this.cart.items && this.cart.items.sort((a, b) => b.item_id - a.item_id) || [];

                if (this.maxItemsToDisplay > 0) {
                    this.cartItems = this.cartItems.slice(0, parseInt(this.maxItemsToDisplay, 10));
                }
            },
            deleteItemFromCart(itemId) {
                this.isLoading = true;

                const formKey = hyva.getFormKey();
                const postUrl = BASE_URL + 'checkout/sidebar/removeItem/';

                fetch(postUrl, {
                    "headers": {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    },
                    "body": "form_key=" + formKey + "&item_id=" + itemId,
                    "method": "POST",
                    "mode": "cors",
                    "credentials": "include"
                }).then(response => {
                    if (response.redirected) {
                        window.location.href = response.url;
                    } else if (response.ok) {
                        return response.json();
                    } else {
                        window.dispatchMessages && window.dispatchMessages([{
                            type: 'warning',
                            text: '<?= $escaper->escapeJs(__('Could not remove item from quote.')) ?>'
                        }]);
                        this.isLoading = false;
                    }
                }).then(result => {
                    window.dispatchMessages && window.dispatchMessages([{
                        type: result.success ? 'success' : 'error',
                        text: result.success
                            ? '<?= $escaper->escapeJs(__('You removed the item.')) ?>'
                            : result.error_message
                    }], result.success ? 5000 : 0)
                    window.dispatchEvent(new CustomEvent('reload-customer-section-data'));
                });
            },
            scrollLock(use = true) {
                document.body.style.overflow = use ? "hidden" : "";
            },
            getSectionDataExtraActions() {
                if (!this.cart.extra_actions) {
                    return '';
                }

                const contentNode = document.createElement('div');
                contentNode.innerHTML = this.cart.extra_actions;

                hyva.activateScripts(contentNode);

                return contentNode.innerHTML;
            }
        }
    }
</script>
<div x-data="initCartDrawer()" @private-content-loaded.window="getData($event.detail.data)">
    <?= $block->getChildHtml('cart-drawer.top'); ?>
    <?= $block->getChildHtml('cart-drawer.items.before'); ?>

    <template x-if="!itemsCount">
        <div class="relative px-4 py-6 bg-white border-bs sm:px-6 border-container">
            <?= $escaper->escapeHtml(__('Cart is empty')) ?>
        </div>
    </template>

    <template x-if="itemsCount">
        <div class="relative grid gap-6 sm:gap-8 px-1 py-3 sm:px-3 bg-white border-b border-container overflow-y-auto overscroll-y-contain">
            <template x-for="item in cartItems">
                <div class="flex items-start p-3 space-x-4 transition duration-150 ease-in-out rounded-lg hover:bg-gray-100">
                    <a :href="item.product_url"
                       class="w-1/4"
                       :aria-label="hyva.strf('<?= $escaper->escapeJs(__('Product "%0"')) ?>', item.product_name)"
                    >
                        <img
                                :src="item.product_image.src"
                                :width="item.product_image.width"
                                :height="item.product_image.height"
                                loading="lazy"
                                alt=""
                        />
                    </a>
                    <div class="w-3/4 space-y-2">
                        <div>
                            <p class="text-xl">
                                <span x-html="item.qty"></span> x <span x-html="item.product_name"></span>
                            </p>
                            <p class="text-sm"><span x-html="item.product_sku"></span></p>
                        </div>
                        <template x-for="option in item.options">
                            <div class="pt-2">
                                <p class="font-semibold" x-text="option.label + ':'"></p>
                                <p class="text-secondary" x-html="option.value"></p>
                            </div>
                        </template>
                        <p><span x-html="item.product_price"></span></p>
                        <div class="pt-4">
                            <a :href="item.configure_url"
                               x-show="item.product_type !== 'grouped' && item.is_visible_in_site_visibility"
                               class="inline-flex p-2 mr-2 btn btn-primary"
                               :aria-label="hyva.strf('<?= $escaper->escapeJs(__('Edit product "%0"')) ?>', item.product_name)"
                            >
                                <?= $heroicons->pencilHtml('', 20, 20, ['aria-hidden' => 'true']); ?>
                            </a>
                            <button type="button"
                                    class="inline-flex p-2 btn btn-primary"
                                    @click="deleteItemFromCart(item.item_id)"
                                    :aria-label="hyva.strf('<?= $escaper->escapeJs(__('Remove product "%0" from cart')) ?>', item.product_name)"
                            >
                                <?= $heroicons->trashHtml('', 20, 20, ['aria-hidden' => 'true']); ?>
                            </button>
                        </div>
                    </div>
                </div>
            </template>
        </div>
    </template>
</div>