<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Drawers\Block\Drawer;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var Drawer $block */
/**
 * Tailwind purge...
 * mt-0
 * mr-0
 * ml-0
 * mb-0
 * h-full
 * w-full
 * h-[10rem]
 * md:h-[20rem]
 * w-[30rem]
 * md:w-[40rem]
 */
?>
<div x-data
     class="backdrop z-10"
     x-cloak
     x-show="drawerState('<?= $block->getId() ?>')"
     x-transition:enter="ease-in-out duration-500"
     x-transition:enter-start="opacity-0"
     x-transition:enter-end="opacity-100"
     x-transition:leave="ease-in-out duration-500"
     x-transition:leave-start="opacity-100"
     x-transition:leave-end="opacity-0"
     role="button"
     @click="drawerClose('<?= $block->getId() ?>')"
     aria-label="<?= $escaper->escapeHtmlAttr(__('Close %1', $block->getTitle())) ?>"></div>
<dialog
        x-data
        id="<?= $block->getId() ?>"
        aria-labelledby=""
        class="<?= $block->getClasses() ?> fixed flex flex-col inset-0 z-30 max-w-full transition ease-in-out bg-white gap-y-8 shadow-2xl bg-gray-50 "
        x-show="drawerState('<?= $block->getId() ?>')"
        x-transition:enter="duration-300"
        x-transition:enter-start="<?= $block->getTransitionEnterStart() ?>"
        x-transition:enter-end="<?= $block->getTransitionEnterEnd() ?>"
        x-transition:leave="duration-100"
        x-transition:leave-start="<?= $block->getTransitionLeaveStart() ?>"
        x-transition:leave-end="<?= $block->getTransitionLeaveEnd() ?>"
        @keydown.window.escape="drawerClose('<?= $block->getId() ?>')"
        x-cloak>
    <section class="flex flex-col h-full text-slate-800 max-h-screen">
        <?php if ($header = $block->getDrawerHeader()): ?>
            <header class="relative px-4 py-6 sm:px-6">
                <?= $header ?>
            </header>
        <?php endif ?>
        <?php if ($content = $block->getDrawerContent()): ?>
            <div class="flex-auto relative grid gap-6 sm:gap-8 overflow-y-auto overscroll-y-contain p-2">
                <?= $content ?>
            </div>
        <?php endif ?>
        <?php if ($footer = $block->getDrawerFooter()): ?>
            <footer class="p-2">
                <?= $footer ?>
            </footer>
        <?php endif ?>
    </section>
</dialog>