<?php
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
?>
<button
    x-data
    type="button"
    @click="drawerOpen('hyva-drawers-demo-bottom')"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Open Down Demo')) ?>"
>
    <?= $heroicons->arrowCircleDownHtml('p-3', 48, 48) ?>
</button>